export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'dashboard',
    path: '/dashboard',
    title: '工作台',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'dir',
    componentPath: '/dashboard/overview/index.vue',
    id: 1,
    pid: null,
  },
  {
    name: 'store',
    path: '/store',
    title: '门店',
    requiresAuth: true,
    icon: 'icon-park-outline:application',
    componentPath: '/store/index.vue',
    id: 2,
    pid: null,
  },
  {
    name: 'vehicle',
    path: '/vehicle',
    title: '车辆',
    requiresAuth: true,
    icon: 'icon-park-outline:car',
    componentPath: null,
    id: 3,
    pid: null,
  },
  {
    name: 'vehicleInstance',
    path: '/vehicle/instance',
    title: '车辆实例管理',
    requiresAuth: true,
    icon: 'icon-park-outline:local-pin',
    componentPath: '/vehicle/instance/index.vue',
    id: 30,
    pid: 3,
  },
  {
    name: 'vehicleType',
    path: '/vehicle/type',
    title: '车辆类型管理',
    requiresAuth: true,
    icon: 'icon-park-outline:manual-gear',
    componentPath: '/vehicle/type/index.vue',
    id: 31,
    pid: 3,
  },
  {
    name: 'vehicleTransfer',
    path: '/vehicle/transfer',
    title: '流转管理',
    requiresAuth: true,
    icon: 'icon-park-outline:map-distance',
    componentPath: '/vehicle/transfer/index.vue',
    id: 32,
    pid: 3,
  },
  {
    name: 'tickets',
    path: '/ticket',
    title: '租借单',
    requiresAuth: true,
    icon: 'icon-park-outline:order',
    componentPath: '/store/manage/index.vue',
    id: 4,
    pid: null,
  },
  {
    name: 'openTickets',
    path: '/ticket/open',
    title: '发起租借单',
    requiresAuth: true,
    icon: 'icon-park-outline:file-editing',
    componentPath: '/ticket/open/index.vue',
    id: 40,
    pid: 4,
  },
  {
    name: 'reviewTickets',
    path: '/ticket/list',
    title: '查看租借单',
    requiresAuth: true,
    icon: 'icon-park-outline:list-view',
    componentPath: '/ticket/list/index.vue',
    id: 41,
    pid: 4,
  },
  {
    name: 'setting',
    path: '/setting',
    title: '系统设置',
    requiresAuth: true,
    icon: 'icon-park-outline:setting',
    menuType: 'dir',
    componentPath: null,
    id: 35,
    pid: null,
  },
  {
    name: 'accountSetting',
    path: '/setting/account',
    title: '用户设置',
    requiresAuth: true,
    icon: 'icon-park-outline:every-user',
    componentPath: '/users/index.vue',
    id: 36,
    pid: 35,
  },
  {
    name: 'userCenter',
    path: '/userCenter',
    title: '个人中心',
    requiresAuth: true,
    icon: 'carbon:user-avatar-filled-alt',
    componentPath: '/userCenter/index.vue', // Updated componentPath
    id: 39,
    pid: null,
  },
];
